name: Download and Save

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm i ts-node -g
    - run: ts-node -T download
    - uses: actions/upload-artifact@v2
      with:
        name: latest
        path: ${{ github.workspace }}/latest.txt
